name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Cordova & dependencies
        run: |
          npm install -g cordova
          npm install
      - name: Prepare platforms
        run: cordova prepare android
      - name: Copy build-extras.gradle (jika ada)
        run: cp build-cordova.gradle platforms/android/app/build-extras.gradle
      - name: Build APK
        run: cordova build android --debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: wemos-app-debug
          path: platforms/android/app/build/outputs/apk/debug/*.apk
